### ISSUE TITLE
United front

### ISSUE THREAD

**Issue by oppressedSVTFOEfan** [aucchen/social_democracy_alternate_history#1]
Shouldn`t I be able to do a "united front" here? I have  decent relationship with all the parties involved. Unless this is a statement on the historical infeasibility of such an arrangement. Also it should probably be called the Popular front instead due to the presance of the DDP and Z:
![image](https://github.com/aucchen/social_democracy_alternate_history/assets/148009499/6b66156a-ee0b-440a-b8a3-1f1e246fb38f)
![image](https://github.com/aucchen/social_democracy_alternate_history/assets/148009499/27359463-bb69-48a6-8081-28e12419a4b3)

**Comment by aucchen** [comment]
You're right, it should be possible. There is currently a hidden stat, "communist_coalition", preventing the popular front/united front that can't be changed enough. This will be fixed in the next release.
