### ISSUE TITLE
Panzerkreuser popularity difference

### ISSUE THREAD

**Issue by Seno900** [aucchen/social_democracy_alternate_history#2]
A thing I noticed is that panzerkreuzer_ministry.scene.dry it gives a worker spd increase when you vote no. However, in the  panzerkreuzer.scene.dry if you have Braun you can get the vote to fail. However this doesn't provide a worker spd increase. Not sure if this is intentional or not. (also realized I never chose Braun as chancellor, I thought it was impossible for way too long).

**Comment by aucchen** [comment]
You're right; there should be a workers_spd boost there. This will be updated in the next release.
